FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY ./ ./
RUN chmod +x ./startup.sh
RUN npx prisma generate --schema ./src/prisma/schema.prisma
RUN npm run build
EXPOSE 3000
CMD ["/bin/sh","-c","./startup.sh"]