services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - rcmmndr_production:/var/lib/postgresql/data
volumes:
  rcmmndr_production:
